swagger: '2.0'
info:
  title: {{cookiecutter.app_title}}
  version: "{{cookiecutter.app_version}}"
basePath: {{cookiecutter.app_base_path}}
host: {{cookiecutter.app_host}}
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /path:
    get:
      summary:  first summary
      operationId: app.path
      consumes:
        - application/json
      parameters:
        - in: body
          name: payload
          schema:
              $ref: '#/definitions/Payload'
      responses:
        200:
          description: chart data for the aggregation
          schema:
            $ref: '#/definitions/Response'
definitions:
  Payload:
    type: object
    properties:
      name:
        type: string
      phone:
        type: string
  Response:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
